/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <jni_md.h>
/* Header for class com_hikvision_algorithm_JNIComparator */

#ifndef _Included_com_hikvision_algorithm_JNIComparator
#define _Included_com_hikvision_algorithm_JNIComparator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hikvision_algorithm_JNIComparator
 * Method:    updateAddress
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_hikvision_algorithm_JNIComparator_updateAddress
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_hikvision_algorithm_JNIComparator
 * Method:    compare
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_hikvision_algorithm_JNIComparator_compare
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
