/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <jni_md.h>
/* Header for class jni_Test */

#ifndef _Included_jni_Test
#define _Included_jni_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_JniDot
 * Method:    dot_product_r7
 * Signature: (ILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)[I
 */
JNIEXPORT jintArray JNICALL Java_jni_JniDot_dot_1product_1r7
        (JNIEnv *, jobject, jint, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     jni_JniDot
 * Method:    dot_product
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_jni_JniDot_dot_1product
        (JNIEnv *, jobject, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
