/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_JniDot */

#ifndef _Included_jni_JniDot
#define _Included_jni_JniDot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_JniDot
 * Method:    dotProduct
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_jni_JniDot_dotProduct
        (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jni_JniDot
 * Method:    batchDotProduct
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_jni_JniDot_batchDotProduct
        (JNIEnv *, jobject, jobject, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif