/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <jni_md.h>
/* Header for class jni_test_ArrayCopyTest */

#ifndef _Included_jni_test_ArrayCopyTest
#define _Included_jni_test_ArrayCopyTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_test_ArrayCopyTest
 * Method:    testGetElementFalse
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_jni_test_ArrayCopyTest_testGetElementFalse
  (JNIEnv *, jobject, jlongArray);

/*
 * Class:     jni_test_ArrayCopyTest
 * Method:    testGetElementTrue
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_jni_test_ArrayCopyTest_testGetElementTrue
  (JNIEnv *, jobject, jlongArray);

/*
 * Class:     jni_test_ArrayCopyTest
 * Method:    testGetArrayRegionOne
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_jni_test_ArrayCopyTest_testGetArrayRegionOne
  (JNIEnv *, jobject, jlongArray);

/*
 * Class:     jni_test_ArrayCopyTest
 * Method:    testGetArrayRegionAll
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_jni_test_ArrayCopyTest_testGetArrayRegionAll
  (JNIEnv *, jobject, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
